### ISSUE TITLE
Class wrappers implementation

### ISSUE THREAD

**Issue by sphamba** [ltelab/tstore#11]
Wrap Dask/polars/pd.Dataframes classic functions to be usable by TSDF.
Functions to be chosen together/discuss. 

Definition of TS object constructor arguments
```
tslong = TSLONG (df, id_var=”id”, ts_vars=[], static_vars=[], geom...)
```

- [x] structure Abstract-based class TSwrapper - incl tswide, tslong... compatible seamlessly with Pandas df, Dask df, Polar df, 
- [x] tests

**Comment by charlottegiseleweil** [comment]
@sphamba this is probably ready to close :)
