### ISSUE TITLE
[FEATURE] drop polars and pyarrow TSDF backends

### ISSUE THREAD

**Issue by martibosch** [ltelab/tstore#47]
See https://github.com/ltelab/tstore/pull/42#discussion_r1663908402 and https://github.com/ltelab/tstore/pull/42#discussion_r1663910677

**Comment by charlottegiseleweil** [comment]
Can you confirm @ghiggi and @sphamba that you agree with dropping non-pandas backends ?

**Comment by ghiggi** [comment]
Hey @charlottegiseleweil. We discussed of this subject with @sphamba.
Currently @sphamba enforced that all TSArray columns within a TSDF should have same backend. 
Moving forward he will allow TSArray columns to have different backends. 
TSDF class will inherit from pandas or geopandas (if geometry column is specified) and the backend at TSDF will be dropped ;)
